AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31
  
Resources:
  AWSSDKv3Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs12.x
        - nodejs10.x
      ContentUri: s3://aws-ilt-courses/nodejs-aws-sdk-v3.zip
      LayerName: AWSSDKv3
      RetentionPolicy: Delete

  XRaySDKLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs12.x
        - nodejs10.x
      ContentUri: s3://aws-ilt-courses/nodejs-xray-sdk.zip
      LayerName: XRaySDK
      RetentionPolicy: Delete

  getAllTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      FunctionName: getAllFunction
      Handler: src/handlers/get-all.getAllHandler
      Layers: 
        - !Ref AWSSDKv3Layer
        - !Ref XRaySDKLayer
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Runtime: nodejs14.x
      Timeout: 100
      Tracing: Active
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref restApi

  getByIdTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      FunctionName: getByIdFunction
      Handler: src/handlers/get-by-id.getByIdHandler
      Layers: 
        - !Ref AWSSDKv3Layer
        - !Ref XRaySDKLayer
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Runtime: nodejs14.x
      Timeout: 100
      Tracing: Active
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
            RestApiId: !Ref restApi            

  putTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      FunctionName: putFunction
      Handler: src/handlers/put.putHandler
      Layers: 
        - !Ref AWSSDKv3Layer
        - !Ref XRaySDKLayer
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Runtime: nodejs14.x
      Timeout: 100
      Tracing: Active
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref restApi

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: Author
          AttributeType: S
        - AttributeName: Title
          AttributeType: S
        - AttributeName: Category
          AttributeType: S
        - AttributeName: Year
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes: 
        - IndexName: CategoryGSIndex
          KeySchema:
            - AttributeName: Category
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      KeySchema: 
        - AttributeName: Author
          KeyType: HASH
        - AttributeName: Title
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: YearLSIndex
          KeySchema:
            - AttributeName: Author
              KeyType: HASH
            - AttributeName: Year
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      TableName: Books

  restApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true